config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :photos, except: :delete

  end

  root to: "landing#index"
  get "/contact", to: "users#contact"
  get "/landing", to: "landing#index"

  delete "/projects/:project_id/photos/:id", to: "photos#destroy", as: "delete_photo"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  resources :users

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  mount_uploader :thumbnail, ThumbnailUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @photos = Photo.where(:project_id => @project.id)
    @user = User.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    unless project_params != nil
      Cloudinary::Uploader.upload(project_params)
    end
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      unless project_params != nil
        Cloudinary::Uploader.upload(project_params)
      end

      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end
    def get_photos_for_project
      Photo.find(project_id:@project.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :media, :date, :thumbnail, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 class="newUser">Editing Project</h1>

<%= form_for @project do |f| %>

<div>
  <%= f.text_field :title, placeholder: "Title" , class: "newUser form-control"%>
</div>
<div>
  <%= f.text_field :media, placeholder: "Media" , class: "newUser form-control"%>
</div>
<div>
  <%= f.date_field :date, class: "newUser form-control"%>
</div>
<div>
  <%= f.file_field :thumbnail, placeholder: "Picture URL" ,class: "newUser form-control userPicture"%>
</div>
<div>
  <%= f.text_area :description, placeholder: "Bio" ,class: "newUser form-control userPicture"%>
</div>

<div class="actions newUser">
  <%= f.submit %>
  <%= link_to 'Back', projects_path %>
</div>
<% end %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Projects</h1>

  <body>
      <div class="row">
        <% @projects.each do |project| %>
          <div class="col-sm-3">
            <%= link_to (image_tag project.thumbnail_url(:display)), project, class:"thumbnail" %>
            <p class="thumbTitle"><%= link_to (project.title), project %></p>
            </br>
            </br>
          </div>
        <% end %>
      </div>
  </body>

  </br>
  <% if current_user %>
    <%= link_to 'New Project', new_project_path %>
  <% end %>
  </br>
  </br>
</div>

app/views/projects/new.html.erb
<h1 class="newUser">New Project</h1>

<%= form_for @project do |f| %>

<div>
  <%= f.text_field :title, placeholder: "Title" , class: "newUser form-control"%>
</div>
<div>
  <%= f.text_field :media, placeholder: "Media" , class: "newUser form-control"%>
</div>
<div>
  <%= f.date_field :date, class: "newUser form-control"%>
</div>
<div>
  <%= f.file_field :thumbnail, placeholder: "Picture URL" ,class: "newUser form-control userPicture"%>
</div>
<div>
  <%= f.text_area :description, placeholder: "Bio" ,class: "newUser form-control userPicture"%>
</div>

<div class="actions newUser">
  <%= f.submit %>
  <%= link_to 'Back', projects_path %>
</div>
<% end %>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class"col-sm-8">
      <br>
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active carouselImage">
            <%= image_tag @project.thumbnail_url %>
          </div>

          <% @photos.each do |photo| %>
            <div class="item carouselImage">
              <%=image_tag photo.image_url%>
              <div class="carousel-caption">
                <h3><%= photo.title %></h3>
              </div>
            </div>
          <% end %>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <h1><%= @project.title %></h1>
    <h6><%= @project.media %></h6>
    <h4><%= @project.date %></h4>
    <h4><%= @project.description %></h4>

  </div>
</div>
<% if current_user == @project.user%>
  <%= link_to 'Edit Project', edit_project_path(@project) %> |
  <%= link_to 'view Photos', project_photos_path(@project) %> |
  <%= link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure?' } %>|
<% end %>
</br>
</br>