config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :photos, except: :delete

  end

  root to: "landing#index"
  get "/contact", to: "users#contact"
  get "/landing", to: "landing#index"

  delete "/projects/:project_id/photos/:id", to: "photos#destroy", as: "delete_photo"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  resources :users

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :project

  mount_uploader :image, ImageUploader

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_project


  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
    @photo.project = @project

  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.project = @project
    unless photo_params != nil
      Cloudinary::Uploader.upload(photo_params)
    end
    respond_to do |format|
      if @photo.save
        format.html { redirect_to project_photos_url(@project), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      unless photo_params != nil
        Cloudinary::Uploader.upload(photo_params)
      end
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to project_photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= form_for [@project, @photo] do |f| %>
<div>
  <%= f.text_field :title, placeholder: "Title" , class: "newUser form-control"%>
</div>
<div>
  <%= f.file_field :image,class: "newUser form-control userPicture"%>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>


<%= link_to 'Back', project_photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Photos</h1>
  <div class="row">

    <% @photos.each do |photo| %>
      <div class="col-sm-4">
        <% if photo.project_id == @project.id %>
          <%= image_tag photo.image_url(:display), class:"thumbnail" %>
          <% if current_user %>
            <p class="deletePicture">
              <%= link_to 'Delete Photo', delete_photo_url(@project, photo.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
        <% end %>

      </div>
    <% end %>

  </div>

  </br>
  </br>
  <% if current_user == @project.user%>
    <%= link_to 'Edit Project', edit_project_path(@project) %> |
    <%= link_to 'New Photo', new_project_photo_path %> |
  <% end %>
  </br>
  </br>
</div>

app/views/photos/new.html.erb
<h1 class="newUser">New Photo</h1>

<%= form_for [@project, @photo] do |f| %>
<div>
  <%= f.text_field :title, placeholder: "Title" , class: "newUser form-control"%>
</div>
<div>
  <%= f.file_field :image,class: "newUser form-control userPicture"%>
</div>
<div class="actions newUser">
  <%= f.submit %>
</div>
<% end %>