config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :photos, except: :delete

  end

  root to: "landing#index"
  get "/contact", to: "users#contact"
  get "/landing", to: "landing#index"

  delete "/projects/:project_id/photos/:id", to: "photos#destroy", as: "delete_photo"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post-folio</title>
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" media="screen" title="no title" charset="utf-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" charset="utf-8"></script>
  <link rel="stylesheet" href="https://bootswatch.com/superhero/bootstrap.min.css" >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", "/"%></li>
          <li><%= link_to "Projects", projects_path %></li>
          <li class="dropdown">
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user)%></li>
            <li> <%= link_to "LogOut", logout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "LogIn", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

    <%= yield %>

</body>
</html>